export const PATHS = {
  no_page: "*",
  home: "/",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  product: "/product",
  catagory: "/catagory",
  warehouse: "/warehouse",
  stock: "/stock",
  supplier: "/supplier",
  purchase_order: "/purchase-order",
  sale_order: "/sale-order",
  customer: "/customer",
  shipment: "/shipment",
  employee: "/employee",
  department: "/department",
  payment: "/payment",
  invoice: "/invoice",
};
