export const PATHS = {
  no_page: "*",
  home: "/",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  product: "/product",
  catagory: "/catagory",
  warehouse: "/warehouse",
  stock: "/stock",
  supplier: "/supplier",
  purchase_order: "/purchase-order",
  sale_order: "/sale-order",
  customer: "/customer",
  shipment: "/shipment",
  employee: "/employee",
  department: "/department",
  payment: "/payment",
  invoice: "/invoice",
  roles: "/roles",

  // Supplier/Vendor routes
  supplier_login: "/supplier-login",
  supplier_register: "/supplier-register",
  supplier_dashboard: "/supplier-dashboard",
  supplier_profile: "/supplier-profile",
  supplier_po_requests: "/supplier/po-requests",
  supplier_quotations: "/supplier/quotations",
};
